name: test/auto_merge_and_auto_approve

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  auto-approve-and-merge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Auto approve the pull request
      uses: hmarr/auto-approve-action@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Auto merge the pull request
      uses: peter-evans/enable-pull-request-automerge@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
