name: test shell cmd
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-shell-cmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run shell script
        run: ./.github/script/simple-cmd.sh
        shell: bash
      
