# This is a basic workflow to help you get started with Actions

name: Test env var

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test env var
        run: |
          echo "print GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "print GITHUB_REF: $GITHUB_REF"
          echo "print GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "print GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "print GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "print GITHUB_JOB: $GITHUB_JOB"
          echo "print GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
