# This is a basic workflow to help you get started with Actions

name: Test env var

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  WORKFLOW_CUSTOM_ENV_VAR: workflow env

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-default-env-var:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Test env var
        run: |
          echo "print GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
          echo "print GITHUB_REF: $GITHUB_REF"
          echo "print GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "print GITHUB_BASE_REF: $GITHUB_BASE_REF"
          echo "print GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "print GITHUB_JOB: $GITHUB_JOB"
          echo "print GITHUB_ACTION_REPOSITORY: $GITHUB_ACTION_REPOSITORY"
  test-custom-env-var:
    runs-on: ubuntu-latest
    env:
      JOB_CUSTOM_ENV_VAR: job env
    steps:
      - name: test custom env var
        run: |
          echo "print WORKFLOW_CUSTOM_ENV_VAR: $WORKFLOW_CUSTOM_ENV_VAR"
          echo "print JOB_CUSTOM_ENV_VAR: $JOB_CUSTOM_ENV_VAR"
          echo "print STEP_CUSTOM_ENV_VAR: $STEP_CUSTOM_ENV_VAR"
        env:
          STEP_CUSTOM_ENV_VAR: step env
        
